[project]
name = "raglazyllm"
version = "0.1.0"
description = ""
authors = [
    {name = "trc"}
]
readme = "README.md"
requires-python = "<4.0,>=3.10"
dependencies = [
    "lazyllm (==0.4.1)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
